### ISSUE TITLE
feat: Flower node

### ISSUE THREAD

**Issue by Nilmanduil** [jim-fx/plantarium#103]
Hi! Your generator is amazing and I think a flower node would be incredible.

The parameter I imagine are :
- number of petals
- length of petals
- width of the base of petals
- width of the tip of petals
- color of the petals
- angle of petals from the stem

What do you think about it ?

**Comment by takoyaro** [comment]
This is a really good idea!
Given that we already have a `shape` node how about simplifying your suggestion down to:
```ts
"petalCount":number
"petalShape":shape
"color":color
"angle":number
```

**Comment by jim-fx** [comment]
First of all, thank you for the idea! I have been thinking about something like this for some time now...

The only thing that may be a bit hard to implement is the color, because that is not yet handled anywhere else...

**Comment by jim-fx** [comment]
![Flower Node Mockup](https://raw.githubusercontent.com/jim-fx/plantarium/main/ideas/assets/flower_node.png)

**Comment by takoyaro** [comment]
I personally like the flexibility and antuhenticity of an `instance along stem` node.

It would also be great if it could either take an array of elements `flower|fruit|leaves| etc. in as sometimes you get a few things growing from the same area....aside from coding I tend to my garden regularly and nature does amazing things _along the stem_ ...
